-- ============================================================================
-- Snowflake Production Analytical Queries
-- Execute these in Snowflake Worksheets for longitudinal reporting
-- ============================================================================

-- Query 1: Fires by Region with Risk Breakdown
SELECT
    COALESCE(REGION, 'Global Pacific Rim') AS REGION,
    COUNT(*) AS FIRE_COUNT,
    SUM(HOTSPOT_COUNT) AS TOTAL_HOTSPOTS,
    ROUND(AVG(AVERAGE_FRP), 2) AS MEAN_FRP_MW,
    ROUND(SUM(AREA_KM2), 2) AS AGGREGATE_AREA_KM2,
    ROUND(COUNT(CASE WHEN RISK_LEVEL = 'CRITICAL' THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0), 1) AS PCT_CRITICAL
FROM ANALYTICS.FIRE_CLUSTERS
GROUP BY REGION
ORDER BY FIRE_COUNT DESC;

-- Query 2: Average FRP by Day
SELECT
    DATE(DETECTED_AT) AS FIRE_DATE,
    COUNT(*) AS CLUSTER_COUNT,
    ROUND(AVG(AVERAGE_FRP), 2) AS AVG_FRP,
    ROUND(MAX(MAX_FRP), 2) AS MAX_FRP_OBSERVED,
    ROUND(SUM(AREA_KM2), 2) AS TOTAL_ESTIMATED_AREA_KM2
FROM ANALYTICS.FIRE_CLUSTERS
GROUP BY DATE(DETECTED_AT)
ORDER BY FIRE_DATE ASC;

-- Query 3: Multi-Year Sensor Comparison (VIIRS vs MODIS vs Landsat)
SELECT
    SATELLITE,
    INSTRUMENT,
    COUNT(*) AS TOTAL_OBSERVATIONS,
    ROUND(AVG(FRP), 2) AS AVERAGE_RADIATIVE_POWER_MW,
    ROUND(MAX(FRP), 2) AS PEAK_RADIATIVE_POWER_MW,
    ROUND(COUNT(CASE WHEN CONFIDENCE = 'high' THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS PCT_HIGH_CONFIDENCE
FROM RAW.FIRE_OBSERVATIONS
GROUP BY SATELLITE, INSTRUMENT
ORDER BY TOTAL_OBSERVATIONS DESC;

-- Query 4: Rapid Growth Fires (>15 Hotspots with High Spread Vectors)
SELECT
    C.CLUSTER_ID,
    C.REGION,
    C.HOTSPOT_COUNT,
    C.AREA_KM2,
    C.AVERAGE_FRP,
    C.RISK_LEVEL,
    P.DIRECTION_DEGREES,
    P.WIND_SPEED,
    P.ESTIMATED_DISTANCE_KM AS SIX_HOUR_FORWARD_KM,
    P.CONFIDENCE AS PREDICTION_CONFIDENCE
FROM ANALYTICS.FIRE_CLUSTERS C
JOIN ANALYTICS.SPREAD_PREDICTIONS P ON C.CLUSTER_ID = P.CLUSTER_ID
WHERE C.RISK_LEVEL IN ('HIGH', 'CRITICAL')
  AND P.ESTIMATED_DISTANCE_KM >= 3.0
ORDER BY C.AVERAGE_FRP DESC;
