-- ============================================================================
-- Snowflake Views: Analytical Aggregations & Rollups
-- ============================================================================

USE DATABASE FIRE_SPACE;
USE SCHEMA ANALYTICS;

-- 1. Daily Fire Activity Rollup
CREATE OR REPLACE VIEW V_DAILY_FIRE_ACTIVITY AS
SELECT
    DATE(DETECTED_AT) AS FIRE_DATE,
    COUNT(DISTINCT CLUSTER_ID) AS ACTIVE_CLUSTERS,
    SUM(HOTSPOT_COUNT) AS TOTAL_HOTSPOTS,
    ROUND(SUM(AREA_KM2), 2) AS TOTAL_BURN_AREA_KM2,
    ROUND(AVG(AVERAGE_FRP), 2) AS DAILY_AVG_FRP,
    ROUND(MAX(MAX_FRP), 2) AS PEAK_FRP,
    COUNT(CASE WHEN RISK_LEVEL = 'CRITICAL' THEN 1 END) AS CRITICAL_FIRES,
    COUNT(CASE WHEN RISK_LEVEL = 'HIGH' THEN 1 END) AS HIGH_RISK_FIRES
FROM ANALYTICS.FIRE_CLUSTERS
GROUP BY DATE(DETECTED_AT);

-- 2. Regional Risk Distribution
CREATE OR REPLACE VIEW V_REGIONAL_SUMMARY AS
SELECT
    COALESCE(REGION, 'Global Unassigned') AS REGION,
    COUNT(*) AS TOTAL_FIRE_CLUSTERS,
    SUM(HOTSPOT_COUNT) AS TOTAL_THERMAL_HOTSPOTS,
    ROUND(AVG(AVERAGE_FRP), 2) AS REGIONAL_AVG_FRP,
    ROUND(SUM(AREA_KM2), 2) AS REGIONAL_BURN_AREA_KM2,
    COUNT(CASE WHEN RISK_LEVEL IN ('HIGH', 'CRITICAL') THEN 1 END) AS THREAT_LEVEL_COUNT
FROM ANALYTICS.FIRE_CLUSTERS
GROUP BY REGION;

-- 3. Satellite Sensor Performance Comparison
CREATE OR REPLACE VIEW V_SATELLITE_COMPARISON AS
SELECT
    SATELLITE,
    INSTRUMENT,
    COUNT(*) AS OBSERVATION_COUNT,
    ROUND(AVG(FRP), 2) AS AVG_FRP,
    ROUND(MAX(FRP), 2) AS MAX_FRP,
    COUNT(CASE WHEN CONFIDENCE = 'high' THEN 1 END) AS HIGH_CONFIDENCE_DETECTIONS,
    ROUND(AVG(BRIGHTNESS_TEMPERATURE), 2) AS AVG_BRIGHTNESS_KELVIN
FROM RAW.FIRE_OBSERVATIONS
GROUP BY SATELLITE, INSTRUMENT;
